### ISSUE TITLE
Room joining in vector-android

### ISSUE THREAD

**Issue by mytbk** [vector-im/vector-android#591]
I find that vector-android only has "Start Chat" and "Create room", but it doesn't have a way to join a room. Someone in \#matrix:matrix.org says I can use /join command, so I create an empty room and type "/join \#matrix:matrix.org" to join a room, but the Riot app will crash once before I successfully join a room.

**Comment by ylecollen** [comment]
mytbk  : you have several ways to join a room
-> if it is a public room, tap on the magnifying glass (int the menu of the recents page)
-> if it is a private room, you have to use the /join method

About your crash with "/join #matrix:matrix.org", i don't reproduce it. Could you send a bug report ?

**Comment by ArchangeGabriel** [comment]
@ylecollen I think that mytbk might be in the same case as myself, namely I use my own HS.

Thus, I only have “Start Chat” and “Create room”, the magnifying glass shows nothing (since there is currently no room on my HS), and I don’t know where to enter this `/join #matrix-dev:matrix.org` command. I’ve tried creating a new room and entering this command here, but it doesn’t work. Is that the expected way? It’s very unclear from the non-existent (or non-findable) doc on the subject…

If so, then maybe that’s a federation issue…

**Comment by ArchangeGabriel** [comment]
How, it worked in fact. But took a bit of time…

**Comment by Matrixcoffee** [comment]
Perhaps having a third "Join existing room" option on pressing the big + button would be more intuitive than hiding this functionality in the search screen.

**Comment by ArchangeGabriel** [comment]
@Matrixcoffee Yeah, definitively!
