### ISSUE TITLE
We should keep trying to send messages even if the app is in the background or closed

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-android#594]
From kegan: So I'm getting hate mail from Jenni about vector android not sending messages if you are on bad connectivity and close the app before it successfully sends the message. Is this a known issue?  Related (perhaps): https://vector.im/develop/#/room/#riot:matrix.org/$14754238071654559FuRGU:matrix.org

**Comment by ylecollen** [comment]
It should be fixed with the following fixed (i don't have the logs to reproduce the issue)

1- the application is launched in offline : the client did not resend the events asap the network becomes available again
https://github.com/matrix-org/matrix-android-sdk/commit/5ce64fe6

2- When the network connection is retrieved, some re-sent event did not warn the unsentEventsManager to re-send the next unsent events.  
https://github.com/matrix-org/matrix-android-sdk/commit/0af1c0ebcbe2af834922949abc6213465e60cdb3
